### ISSUE TITLE
Code for MTBench and Just-Eval

### ISSUE THREAD

**Issue by tongwu2020** [uw-nsl/SafeDecoding#1]
Hi, thanks for the great work. 

I would love to ask if you can provide the codes for MTBench and Just Eval codes. Thank you.

**Comment by zhangchen-xu** [comment]
Hi,

Thanks! I used the original evaluation from MTBench and Just Eval, and we do have some "bridging code" to deal with the generation part. I am currently on a travel and will update the code soon after coming back~~
