### ISSUE TITLE
code for AutoDAN, GCG, DeepInception and PAIR attacks

### ISSUE THREAD

**Issue by chenzongxiong** [uw-nsl/SafeDecoding#7]
Dear authors, 

Could you share your implementation about the attacks you used to generate the dataset **[SafeDecoding-Attackers](https://huggingface.co/datasets/flydust/SafeDecoding-Attackers?row=1)**

Thanks very much.

**Comment by zhangchen-xu** [comment]
We follow official implementations and hyperparameters.

Please refer to the official repo of these papers for implementation details:
- GCG: https://github.com/llm-attacks/llm-attacks
- AutoDAN: https://github.com/SheltonLiu-N/AutoDAN
- PAIR: https://github.com/patrickrchao/JailbreakingLLMs
- DeepInception: https://github.com/tmlr-group/DeepInception
